import os
import random
import sqlite3
import string
from argparse import ArgumentParser
from werkzeug.security import generate_password_hash

# setup parser
parser = ArgumentParser(prog = 'usermod',
                        description = f'modify existing user in the database',
                        epilog='passwords are autogenerated')

parser.add_argument('old_username', help='existing user name')
parser.add_argument('-f', '--fake', help='don\'t write to the database', action='store_true')
parser.add_argument('-p', '--password', help='generate new password', action='store_true')
parser.add_argument('-u', '--username', help='new username')

# get arguments
args = parser.parse_args()
old_username = args.old_username
username = args.username
password = True if args.password else False
new_password = None
password_raw = None
fake = True if args.fake else False

# compute raw password and secure password
if password:
    character_list = string.ascii_letters + string.digits + string.punctuation
    password_raw = ''.join(random.choice(character_list) for x in range(42))
    new_password = generate_password_hash(password_raw)

if not fake:
    # modify user
    DATABASE = os.path.join('instance', 'flaskr.sqlite')
    with sqlite3.connect(DATABASE) as conn:

        if password:
            if username:
                conn.execute('UPDATE user SET username = ?, password = ? WHERE username = ?', (username, new_password, old_username))
            else:
                username = old_username
                conn.execute('UPDATE user SET password = ? WHERE username = ?', (new_password, username))
        else:
            if username:
                conn.execute('UPDATE user SET username = ? WHERE username = ?', (username, old_username))
            else:
                print('Nothing to do here')
                quit(1)


        conn.commit()

# display information written to database
print(f'username: {username}')

if password:
    print(f'password: {password_raw}')
    print()
    print('please add this information into your Password Manager')

